import time
defframe = ["0","0","0","0","0","0","0","0",
            "0","0","0","0","0","0","0","0",
            "0","0","0","0","0","0","0","0",
            "0","0","0","0","0","0","0","0",
            "0","0","0","0","0","0","0","0",
            "0","0","0","0","0","0","0","0",
            "0","0","0","0","0","0","0","0"] #The old way of storing.
curframe = ""
#Lovely 8x7 frame.

frames = ["XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX",
          "XXXXXXXX,XXOXXOXX,XXOXXOXX,XXXXXXXX,XOXXXXOX,XXOOOOXX,XXXXXXXX",
          "XXXXXXXX,XXOXXOXX,XXOXXOXX,XXXXXXXX,XOXXXXOX,XXOOOOXX,XXXXXXXX",
          "XXXXXXXX,XXOXXOXX,XXOXXOXX,XXXXXXXX,XOXXXXOX,XXOOOOXX,XXXXXXXX",
          "XXXXXXXX,XXOXXOXX,XXOXXOXX,XXXXXXXX,XOXXXXOX,XXOOOOXX,XXXXXXXX",
          "XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XOXXXXOX,XXOOOOXX,XXXXXXXX",
          "XXXXXXXX,XXOXXOXX,XXOXXOXX,XXXXXXXX,XOXXXXOX,XXOOOOXX,XXXXXXXX",
          "XXXXXXXX,XXOXXOXX,XXOXXOXX,XXXXXXXX,XOXXXXOX,XXOOOOXX,XXXXXXXX",
          "XXXXXXXX,XXOXXOXX,XXOXXOXX,XXXXXXXX,XOXXXXOX,XXOOOOXX,XXXXXXXX",
          "XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XOOOOOOX,XXXXXXXX",
          "XXXXXXXX,XXOXXOXX,XOXXXXOX,XOXXXXOX,XXXXXXXX,XXOOOOXX,XOXXXXOX",
          "XXXXXXXX,XXOXXOXX,XOXXXXOX,XXXXXXXX,XOXXXXOX,XXOOOOXX,XOXXXXOX",
          "XXXXXXXX,XXOXXOXX,XOXXXXOX,XOXXXXOX,XXXXXXXX,XXOOOOXX,XOXXXXOX",
          "XXXXXXXX,XXOXXOXX,XOXXXXOX,XXXXXXXX,XOXXXXOX,XXOOOOXX,XOXXXXOX",
          "XXXXXXXX,XXOXXOXX,XOXXXXOX,XOXXXXOX,XXXXXXXX,XXOOOOXX,XOXXXXOX",
          "XXXXXXXX,XXOXXOXX,XOXXXXOX,XXXXXXXX,XOXXXXOX,XXOOOOXX,XOXXXXOX",
          "XXXXXXXX,XXOXXOXX,XOXXXXOX,XOXXXXOX,XXXXXXXX,XXOOOOXX,XOXXXXOX",
          "XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XOOOOOOX,XXXXXXXX",
          "OXOXXOXO,XOXXXXOX,OXOXXOXO,XXXXXXXX,XXXXXXXX,XOOOOOOX,XXXXXXXX",
          "XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX",
          "XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX",
          "XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX",
          "XXXOOXXX,XXXXXXXX,XXXXXXXX,OXXXXXXO,XXXXXXXX,XXXXXXXX,XXXOOXXX",
          "XXXOOXXX,XXXOOXXX,XXXXXXXX,OOXXXXOO,XXXXXXXX,XXXOOXXX,XXXOOXXX",
          "XXXOOXXX,XXXOOXXX,XXXOOXXX,OOOXXOOO,XXXOOXXX,XXXOOXXX,XXXOOXXX",
          "XXXOOXXX,XXXOOXXX,XXXOOXXX,OOOOOOOO,XXXOOXXX,XXXOOXXX,XXXOOXXX",
          "OXXOOXXO,XXXOOXXX,XXXOOXXX,OOOOOOOO,XXXOOXXX,XXXOOXXX,OXXOOXXO",
          "OXXOOXOO,OXXOOXXX,XXXOOXXX,OOOOOOOO,XXXOOXXX,XXXOOXXO,OOXOOXXO",
          "OXXOOOOO,OXXOOXXX,OXXOOXXX,OOOOOOOO,XXXOOXXO,XXXOOXXO,OOOOOXXO",]
framerate = 30 #X XI mean its not technically framerate, as it's just how many milliseconds between frames.

for i in range(len(frames)):
    print("\n\n\n\n\n\n\n\n\n\n")
    for a in frames[i]:
        if not a == ",":
            curframe += a
        else:
            curframe += "\n"
    print(curframe)
    curframe = ""
    time.sleep(framerate/100)
